name: restaurante-local

services:
  # --- Frontend: React/Vite ---
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5188:5188"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_BACKEND_URL=http://backend:3010
    depends_on:
      - db

  # --- Backend: Node.js/Express ---
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "3010:3010"
    volumes:
      - ./backend:/app
      - /app/node_modules
    #SE COMENTA PORQUE LAS VARIABLES YA ESTÁN EN "environment" Y EVITA ERROR DE RUTA
    #env_file:
    #  - ./backend/.env
    environment:
      - DATABASE_URL=postgresql://local_user:local_password@db:5432/restaurante_local
      - PORT=3010
      - COMPANY_NAME=Restaurante Local
      - COMPANY_RUC=20600000001
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

  # --- Base de Datos: PostgreSQL ---
  db:
    image: postgres:16-alpine
    ports:
      - "5445:5432"
    environment:
      - POSTGRES_USER=local_user
      - POSTGRES_PASSWORD=local_password
      - POSTGRES_DB=restaurante_local
    volumes:
      - postgres_data_restaurante_local:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U local_user -d restaurante_local" ]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data_restaurante_local:

